2025-05-06 12:45:53,324 - INFO - Iniciando serviço de monitoramento...
2025-05-06 12:45:53,340 - ERROR - Erro na requisição do token: 500 Server Error: Internal Server Error for url: http://164.72.15.30:5050/token
2025-05-06 12:46:53,408 - ERROR - Erro na requisição do token: 500 Server Error: Internal Server Error for url: http://164.72.15.30:5050/token
2025-05-06 12:47:53,443 - ERROR - Erro na requisição do token: 500 Server Error: Internal Server Error for url: http://164.72.15.30:5050/token
2025-05-06 12:48:53,508 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fc2c8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 12:49:53,573 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fc2cf10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 12:50:53,636 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fbec940>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 12:51:53,701 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fc2c790>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 12:52:53,762 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fc18f70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 12:54:59,233 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fbec5b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-05-06 12:56:02,369 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fbf3370>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-05-06 12:57:02,432 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fbf3d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 12:58:02,497 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fbf39a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 12:59:02,562 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fc18d60>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:00:02,595 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fbece20>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:01:02,658 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fbec940>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:02:02,695 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fa14fc2c250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:03:03,451 - ERROR - Erro na requisição do token: 500 Server Error: Internal Server Error for url: http://164.72.15.30:5050/token
2025-05-06 13:04:03,533 - ERROR - Erro na requisição do token: 500 Server Error: Internal Server Error for url: http://164.72.15.30:5050/token
2025-05-06 13:05:03,609 - ERROR - Erro na requisição do token: 500 Server Error: Internal Server Error for url: http://164.72.15.30:5050/token
2025-05-06 13:06:04,257 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:07:04,314 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:08:04,330 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:08:26,752 - INFO - Iniciando serviço de monitoramento...
2025-05-06 13:08:26,808 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:09:10,146 - INFO - Iniciando serviço de monitoramento...
2025-05-06 13:09:10,243 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:10:10,321 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:11:10,392 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:12:10,469 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:13:10,545 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:13:57,618 - INFO - Iniciando serviço de monitoramento...
2025-05-06 13:13:57,637 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:14:57,704 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:15:57,737 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:16:57,762 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:17:57,780 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:18:57,884 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:19:57,908 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:20:57,950 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:21:58,031 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:22:58,101 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:23:58,151 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:24:58,195 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:25:58,225 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 13:26:58,291 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a769370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:27:58,355 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a769ee0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:28:58,420 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a71d910>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:29:58,485 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a769bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:31:16,513 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a7478b0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-05-06 13:32:17,057 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a71d5e0>: Failed to establish a new connection: [Errno 113] No route to host'))
2025-05-06 13:33:17,092 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a723340>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:34:17,156 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a723d30>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:35:17,220 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a723c10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:36:17,284 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a747400>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:37:17,338 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a71df70>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:38:17,403 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a71d250>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:39:17,468 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a769af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:40:17,534 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a72d760>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:41:17,540 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a71dd00>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:42:17,602 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a71d2e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:43:17,618 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a7478e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:44:17,624 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a7239a0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:45:17,668 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a72d040>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:46:17,733 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a723ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:47:17,796 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a723370>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:48:17,828 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a71d100>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:49:17,892 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a71d640>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:50:17,956 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a7697c0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:51:18,022 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a738190>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:52:18,060 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a71d8e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:53:18,125 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a71de80>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:54:18,164 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a723040>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:55:18,227 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a723f40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:56:18,244 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a72ddc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:57:18,310 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a723af0>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:58:18,344 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a723400>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 13:59:18,408 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a71df40>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 14:00:18,473 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a71d190>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 14:01:18,539 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a72dc10>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 14:02:18,600 - ERROR - Erro na requisição do token: HTTPConnectionPool(host='164.72.15.30', port=5050): Max retries exceeded with url: /token (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f507a72d610>: Failed to establish a new connection: [Errno 111] Connection refused'))
2025-05-06 14:03:18,728 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 14:04:18,745 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 14:05:18,797 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 14:06:18,875 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 14:07:18,956 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 14:08:19,037 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 14:09:19,090 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 14:10:19,152 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 14:11:19,164 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 14:12:19,232 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 14:13:19,313 - ERROR - Erro na requisição do token: 401 Client Error: Unauthorized for url: http://164.72.15.30:5050/token
2025-05-06 14:14:19,736 - INFO - Token de autenticação obtido com sucesso
2025-05-06 14:14:19,765 - INFO - Nenhum novo ataque detectado
2025-05-06 14:15:19,846 - INFO - Nenhum novo ataque detectado
2025-05-06 14:16:19,889 - INFO - Nenhum novo ataque detectado
2025-05-06 14:17:19,963 - INFO - Nenhum novo ataque detectado
2025-05-06 14:18:20,045 - INFO - Nenhum novo ataque detectado
2025-05-06 14:19:20,123 - INFO - Nenhum novo ataque detectado
2025-05-06 14:20:20,205 - INFO - Nenhum novo ataque detectado
2025-05-06 14:21:20,287 - INFO - Nenhum novo ataque detectado
2025-05-06 14:22:20,315 - INFO - Nenhum novo ataque detectado
2025-05-06 14:23:20,369 - INFO - Nenhum novo ataque detectado
2025-05-06 14:24:20,450 - INFO - Nenhum novo ataque detectado
2025-05-06 14:25:20,532 - INFO - Nenhum novo ataque detectado
2025-05-06 14:26:20,614 - INFO - Nenhum novo ataque detectado
2025-05-06 14:27:20,696 - INFO - Nenhum novo ataque detectado
2025-05-06 14:28:20,779 - INFO - Nenhum novo ataque detectado
2025-05-06 14:29:20,861 - INFO - Nenhum novo ataque detectado
2025-05-06 14:30:20,917 - INFO - Nenhum novo ataque detectado
2025-05-06 14:31:20,998 - INFO - Nenhum novo ataque detectado
2025-05-06 14:32:21,080 - INFO - Nenhum novo ataque detectado
2025-05-06 14:33:21,162 - INFO - Nenhum novo ataque detectado
2025-05-06 14:34:21,209 - INFO - Nenhum novo ataque detectado
2025-05-06 14:35:21,287 - INFO - Nenhum novo ataque detectado
2025-05-06 14:36:21,309 - INFO - Nenhum novo ataque detectado
2025-05-06 14:37:21,380 - INFO - Nenhum novo ataque detectado
2025-05-06 14:38:21,451 - INFO - Nenhum novo ataque detectado
2025-05-06 14:39:21,517 - INFO - Nenhum novo ataque detectado
2025-05-06 14:40:21,596 - INFO - Nenhum novo ataque detectado
2025-05-06 14:41:21,632 - INFO - Encontrados 3 IPs únicos de ataques
2025-05-06 14:41:21,633 - INFO - Detectada mudança na lista de IPs
2025-05-06 14:41:21,634 - INFO - IPs anteriores: set()
2025-05-06 14:41:21,635 - INFO - Novos IPs: {'pi@164.72.15.11', 'pi@164.72.15.13', 'pi@164.72.15.10'}
2025-05-06 14:41:21,636 - ERROR - Erro no loop principal: [Errno 13] Permission denied: 'state/state.json'
2025-05-06 14:41:21,636 - INFO - Aguardando 60 segundos antes de tentar novamente
2025-05-06 14:42:21,738 - INFO - Encontrados 3 IPs únicos de ataques
2025-05-06 14:42:21,740 - INFO - Detectada mudança na lista de IPs
2025-05-06 14:42:21,740 - INFO - IPs anteriores: set()
2025-05-06 14:42:21,741 - INFO - Novos IPs: {'pi@164.72.15.11', 'pi@164.72.15.13', 'pi@164.72.15.10'}
2025-05-06 14:42:21,741 - ERROR - Erro no loop principal: [Errno 13] Permission denied: 'state/state.json'
2025-05-06 14:42:21,741 - INFO - Aguardando 120 segundos antes de tentar novamente
2025-05-06 14:43:30,429 - INFO - Iniciando serviço de monitoramento...
2025-05-06 14:43:30,970 - INFO - Token de autenticação obtido com sucesso
2025-05-06 14:43:31,013 - INFO - Encontrados 3 IPs únicos de ataques
2025-05-06 14:43:31,014 - INFO - Detectada mudança na lista de IPs
2025-05-06 14:43:31,015 - INFO - IPs anteriores: set()
2025-05-06 14:43:31,015 - INFO - Novos IPs: {'pi@164.72.15.11', 'pi@164.72.15.13', 'pi@164.72.15.10'}
2025-05-06 14:43:31,016 - ERROR - Erro no loop principal: [Errno 13] Permission denied: 'state/state.json'
2025-05-06 14:43:31,016 - INFO - Aguardando 60 segundos antes de tentar novamente
2025-05-06 14:44:31,381 - INFO - Encontrados 3 IPs únicos de ataques
2025-05-06 14:44:31,382 - INFO - Detectada mudança na lista de IPs
2025-05-06 14:44:31,382 - INFO - IPs anteriores: set()
2025-05-06 14:44:31,382 - INFO - Novos IPs: {'pi@164.72.15.11', 'pi@164.72.15.13', 'pi@164.72.15.10'}
2025-05-06 14:44:31,383 - ERROR - Erro no loop principal: [Errno 13] Permission denied: 'state/state.json'
2025-05-06 14:44:31,383 - INFO - Aguardando 120 segundos antes de tentar novamente
